version: '3'
services:
  etude_shopify_php_laravel:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - SHOPIFY_API_KEY=<your clientid>
        - PORT=8081
        - SHOPIFY_APP_SCOPES=write_customers,write_orders,write_products
        - HOST_NAME=<your hostname>
    environment:
      - SHOPIFY_API_KEY=<your clientid>
      - PORT=8081
      - SHOPIFY_APP_SCOPES=write_customers,write_orders,write_products
      - HOST_NAME=<your hostname>
    ports:
      - "8081:8081"
    volumes:
      - ./web:/app
